## **Numpy**

In [2]:
import numpy as np

In [3]:
arr_1d = [1,2,3,4,5]
np.array(arr_1d)

array([1, 2, 3, 4, 5])

In [6]:
arr_2d = np.array([[2,1,5],[5,6,7],[3,5,6]])
arr_2d

array([[2, 1, 5],
       [5, 6, 7],
       [3, 5, 6]])

In [13]:
zero_matrix = np.zeros((2,3),dtype='int')
zero_matrix

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
ones_matrix = np.ones((2,3),dtype='int')
ones_matrix

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arithmetic Operation in Numpy

In [22]:
arr1 = np.array([1,2,4])
arr2 = np.array([4,5,6])
add_arr = np.add(arr1,arr2)
mul_arr = np.multiply(arr1,arr2)

arr1 - 10*arr1/100

array([0.9, 1.8, 3.6])

## Matrix Operations

In [34]:
matrix_1 = np.array([[1,2,3],[4,5,6]])
matrix_2 = np.array([[4,5,6],[7,8,9],[2,3,4]])
print(f"Matrix 1 : \n {matrix_1} \n Matrix 2 :\n {matrix_2} ")
result = np.matmul(matrix_1,matrix_2)
print(f"Multiplication : \n {result} ")



Matrix 1 : 
 [[1 2 3]
 [4 5 6]] 
 Matrix 2 :
 [[4 5 6]
 [7 8 9]
 [2 3 4]] 
Multiplication : 
 [[24 30 36]
 [63 78 93]] 


In [35]:
result[0][0] = 20

In [36]:
result

array([[20, 30, 36],
       [63, 78, 93]])

## Indexing and Slicing

In [38]:
print(arr1[::-1])

[4 2 1]


## Statistical Operations

In [44]:
arr = np.array([1,2,5,6,3,4,5])

In [45]:
np.median(arr)

4.0

In [46]:
arr.mean()

3.7142857142857144

## Standard Deviation
- it's a deviation between all items in the list of our data
- how much each item in our list is deviated from mean

In [56]:
import pygame

def play_mp3(file_path):
    pygame.init()
    pygame.mixer.init()
    pygame.mixer.music.load(file_path)
    pygame.mixer.music.play()

    # Allow the music to play
    pygame.time.wait(5000)  # Use wait instead of delay for accurate timing

    pygame.mixer.music.stop()
    pygame.quit()

def error_handler_decorator(func):
    def wrapper():
        try:
            # Initialize pygame mixer before running the function
            pygame.init()
            pygame.mixer.init()

            # Attempt to run the provided function
            result = func()
            print("Successful")
            play_mp3("raj.mp3")
            return result
        except Exception as e:
            # Handle the exception and print an error message
            pygame.mixer.Sound("nic.mp3").play()
            print(f"Error: {e}")
        finally:
            # Quit pygame mixer in the finally block to ensure cleanup
            pygame.mixer.quit()
    
    return wrapper

# Applying the decorator to a sample function
@error_handler_decorator
def sample_function():
    # This is a sample function that might raise an error
    x = 1 / 0

# Calling the decorated function
sample_function()


Error: division by zero
